-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "categorizables" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "description" TEXT,
  "is_active" INTEGER not null default 1,
  "categorizable_id" INTEGER not null default 0,
  "categorizable_type" TEXT not null,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "categorizables_owner_slug_unique" ON "categorizables" ("categorizable_type", "categorizable_id", "slug");
