-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "delivery_stops" ADD COLUMN "type" TEXT CHECK ("type" IN ('pickup', 'dropoff')) not null default 'dropoff';
